### ISSUE TITLE
app.py returns a dependency error - File "app.py", line 18, in <module>     from werkzeug.datastructures import ImmutableDict ImportError: No module named werkzeug.datastructures

### ISSUE THREAD

**Issue by SoCohesive** [sgp715/simple_image_annotator#5]
Hello!

If i run app.py it returns an error: 

Traceback (most recent call last):
  File "app.py", line 18, in <module>
    from werkzeug.datastructures import ImmutableDict
ImportError: No module named werkzeug.datastructures

I have werkzueg installed and in my python site-packages folder. Is there something else you recommend to do?

**Comment by sgp715** [comment]
Hello!

Hmm I am not able to reproduce the problem on my machine.

Sounds like it could be a python version issue? Have you already tried the things suggested here: https://stackoverflow.com/questions/40231354/cant-import-flask-because-werkzeug? 

Maybe try creating a virtualenv using Python 3.
